language: node_js
cache: yarn

sudo: required
dist: trusty

node_js:
  - "4"
  - "6"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: grunt test-ci --ci
